#pragma once
class MessageLobby
{
public:
	enum Hive
	{
		GVS_DOWNLOAD_COMPLETE,
		HIVE_LOGIN_COMPLETE,
	};
	enum Stage
	{
		INTRO_COMPLETE,
		ASSETDOWN_COMPLETE,
		LOGIN_COMPLETE,
		SERVER_SELECTCOMPLETE,
		BACKTO_SERVER_SELECT,
		ENTER_INGAME,
		INGAME_LOAD_COMPLETE // FIX:
	};
};