#pragma once
class MessageLobby
{
public:
	enum Hive
	{
		GVS_DOWNLOAD_COMPLETE,
		HIVE_LOGIN_COMPLETE,
	};
	enum Stage
	{
		INTRO_COMPLETE,
		ENTER_ASSETDOWNLOAD_STAGE,
		ASSETDOWN_COMPLETE,
		LOGIN_COMPLETE,
		ENTER_SERVERSELECT_STAGE,
		SERVER_SELECTCOMPLETE,
		ENTER_CHARACTERSELECT_STAGE,
		BACKTO_SERVER_SELECT,
		ENTER_INGAME,
		INGAME_LOAD_COMPLETE
	};
};